<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{b581cc96-544a-4433-b34c-693c6f010412}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	dummy :BOOL := FALSE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//dummy := GVL.G_FromYaskawa[0].1;
//int_check();

Robot_IO_mapping();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="7" Count="0" />
      <LineId Id="14" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>